server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/????? ???? ????
spring.datasource.username=postgres
spring.datasource.password=????? ???? ??????

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false # Good practice to avoid N+1 issues in web layer

# For H2 in-memory database (useful for development/testing if you don't want PostgreSQL running)
# spring.h2.console.enabled=true
# spring.datasource.url=jdbc:h2:mem:onlineshopsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# SQL initialization (for initial data loading from data.sql)
spring.sql.init.mode=always
spring.sql.init.platform=postgres